#Image seras issus d'un image ubuntu
FROM ubuntu:bionic

#installe bind9 sur notre image
RUN apt update && apt upgrade -y && apt install bind9 bind9utils -y

#Copie les fichiers de configuration pré-configurer

COPY named.conf /etc/bind/
COPY named.conf.options /etc/bind/
COPY named.conf.default_zones /etc/bind/
COPY named.conf.local /etc/bind/

COPY db.tl1-3.ephec-ti.be /etc/bind/zones/

CMD named -g


