From ubuntu 

# verification de Maj, installation de Maj 
RUN apt update && apt upgrade -y 
&& DEBIAN_FRONTEND=noninteractive apt-get -y -q 
&&install postfix mailutils  -y
&& apt-get -y install nano
&&rm /etc/postfix/main.cf

#Copie les fichiers de configuration pré-configurer


#Ouverture des ports 
EXPOSE 25 587
